### ISSUE TITLE
Could you help me ? please

### ISSUE THREAD

**Issue by phuclb2306** [DJ-Raven/java-swing-chat-application#1]
hello bro. I tried send voice method that i saw in your project https://www.youtube.com/watch?v=QfUREEp0kRk&t=212s
from client to server with binary data (byteArray) in java socket.IO but it not worked and not show error.  when i used "emit" method from client . so how to send binary data to server ?. could you help me this problem ?.Im watch your project to coding for my final exam in my university. 
Client 
![image](https://user-images.githubusercontent.com/66561370/146832051-8fcb6946-9084-4010-b64d-26e72e230bc0.png)
Server 
![image](https://user-images.githubusercontent.com/66561370/146832111-beeb3fea-3618-4471-998c-5878c25ee135.png)

**Comment by DJ-Raven** [comment]
in server you add event "send_voice" so in client you should emit
"send_voice" not "voice".
but you still got error. because soketio is limit data to send package to
server. you need send 2000 byte array per package to server.
like code i has send image for example.
