### ISSUE TITLE
Can't use the other tabs, whenever I click on the other tabs all the users become "Unknown User" any idea how to fix this?

### ISSUE THREAD

**Issue by Jojojokster** [DJ-Raven/java-swing-chat-application#3]
![image](https://github.com/DJ-Raven/java-swing-chat-application/assets/35631391/2ea0773d-26b7-415b-8b16-69a1c54fa98b)
![image](https://github.com/DJ-Raven/java-swing-chat-application/assets/35631391/a3cdf23a-fb27-4194-83c6-1809bf1b7ea0)
![image](https://github.com/DJ-Raven/java-swing-chat-application/assets/35631391/5a894c20-ead9-4687-a132-8fd5a7b33310)

**Comment by DJ-Raven** [comment]
This project implements only the first tabs 😪. so you can remove other tabs.
